## Example

The Originating Agency Identifer (ORI) uniquely identifies the 19,000+ law enforcement agencies in the FBI data. If no api_key is passed in `FBI()`, your environment variable `FBI_API_KEY` is automatically invoked. 

- `get_metadata()`: Extract metadata of agencies by state, including but not limited to the ORIs.
- `get_agency_metrics()`: Extract the number of sworn and non-sworn officers in the police agency (and the total population they serve). The `ori` and `year` parameters accept both a string and a list of strings. 
- `get_crime_statistics()`: Extract monthly crime statistics. The `ori`, `year`, and `offense` parameters accept both a string and a list of strings.

In [1]:
from fbi_api import FBI

api = FBI()

In [ ]:
ori = "NY0303000"
offenses = ["Violent Crimes", "Aggravated Assault", "Burglary", "Larceny"]

metadata = api.get_metadata("all")

agency_metrics = api.get_agency_metrics(ori = ori, year = 2024)

nyc_crime_statistics = api.get_crime_statistics(ori = ori, year = [2022, 2024], offense = offenses)

Extracting metadata for all states: 100%|██████████| 51/51 [00:32<00:00,  1.56it/s]

Success!
Executing 1 query...

100%|██████████| 1/1 [00:01<00:00,  1.89s/it]

Executing 8 queries...

100%|██████████| 8/8 [00:02<00:00,  3.20it/s]

In [3]:
metadata.head()

,ori,counties,is_nibrs,latitude,longitude,state_abbr,state_name,agency_name,agency_type_name,nibrs_start_date
0,AL0430000,LEE,True,32.604064,-85.353048,AL,Alabama,Lee County Sheriff's Office,County,2012-04-01
1,AL0430200,LEE,True,32.604064,-85.353048,AL,Alabama,Opelika Police Department,City,2021-01-01
2,AL0430100,LEE,True,32.608086,-85.475136,AL,Alabama,Auburn Police Department,City,2020-12-01
3,AL0070300,BIBB,True,33.015893,-87.127148,AL,Alabama,West Blocton Police Department,City,2020-01-01
4,AL0070200,BIBB,True,33.015893,-87.127148,AL,Alabama,Brent Police Department,City,2020-01-01

In [4]:
agency_metrics.head()

,ori,year,population,num_male_officers,num_female_officers,num_male_civilians,num_female_civilians,last_refresh_date
0,NY0303000,2024,8299271,26248,7059,5007,8490,03/15/2026

In [5]:
nyc_crime_statistics.head()

         ori  month  year         offense  count last_refresh_date
0  NY0303000      1  2022  Violent Crimes   4345        03/15/2026
1  NY0303000      2  2022  Violent Crimes   4287        03/15/2026
2  NY0303000      3  2022  Violent Crimes   4834        03/15/2026
3  NY0303000      4  2022  Violent Crimes   4819        03/15/2026
4  NY0303000      5  2022  Violent Crimes   5561        03/15/2026